### ISSUE TITLE
ModuleNotFoundError: No module named 'agents'

### ISSUE THREAD

**Issue by iuhiyuh** [Thinklab-SJTU/Bench2Drive#12]
Hi, i follow this [EVAL Doc](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/EVAL_IN_CARLA.md)  
but in Bench2Drive/scenario_runner/srunner/scenariomanager/carla_data_provider.py line 22, raise an error:

```shell
from agents.navigation.global_route_planner import GlobalRoutePlanner
ModuleNotFoundError: No module named 'agents'
```
Do i need to rebuild the bench2drivezoo or something else？

**Comment by jayyoung0802** [comment]
Hi, you need to set PYTHONPATH and  SCENARIO_RUNNER_ROOT, just like [run_evaluation.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation.sh#L9-L10)

**Comment by iuhiyuh** [comment]
```shell
> bash leaderboard/scripts/run_evaluation_debug.sh
leaderboard/leaderboard/leaderboard_evaluator.py:21: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/home/gzx/workspace/bench2drive/carla/CarlaUE4.sh -RenderOffScreen -nosound -carla-rpc-port=30000 -graphicsadapter=0 None
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
load_world success , attempts=0
traffic_manager init success, try_time=0
leaderboard/leaderboard/leaderboard_evaluator.py:115: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.10'):
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 559, in <module>
    main()
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 548, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 121, in __init__
    self.module_agent = importlib.import_module(module_name)
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gzx/workspace/bench2drive/Bench2Drive/leaderboard/team_code/vad_b2d_agent.py", line 20, in <module>
    from mmcv import Config
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/__init__.py", line 8, in <module>
    from .core.bbox.coder.nms_free_coder import NMSFreeCoder
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/core/post_processing/__init__.py", line 3, in <module>
    from .box3d_nms import aligned_3d_nms, box3d_multiclass_nms, circle_nms
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/core/post_processing/box3d_nms.py", line 6, in <module>
    from mmcv.ops.iou3d_det.iou3d_utils import nms_gpu, nms_normal_gpu
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/ops/__init__.py", line 2, in <module>
    from .modulated_deform_conv import (ModulatedDeformConv2d,
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/ops/modulated_deform_conv.py", line 11, in <module>
    from ..models import CONV_LAYERS
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/models/__init__.py", line 9, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/models/dense_heads/__init__.py", line 6, in <module>
    from .occ_head import OccHead
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/models/dense_heads/occ_head.py", line 16, in <module>
    from .occ_head_plugin import MLP, BevFeatureSlicer, SimpleConv2d, CVT_Decoder, Bottleneck, UpsamplingAdd, \
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/models/dense_heads/occ_head_plugin/__init__.py", line 2, in <module>
    from .metrics import *
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/site-packages/mmcv-0.0.1-py3.8-linux-x86_64.egg/mmcv/models/dense_heads/occ_head_plugin/metrics.py", line 10, in <module>
    from mmcv.metrics.metric import Metric
ModuleNotFoundError: No module named 'mmcv.metrics'

```

**Comment by iuhiyuh** [comment]
> Hi, you need to set PYTHONPATH and SCENARIO_RUNNER_ROOT, just like [run_evaluation.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation.sh#L9-L10)

thks， but i've encountered another error:
```shell
> bash leaderboard/scripts/run_evaluation_debug.sh
leaderboard/leaderboard/leaderboard_evaluator.py:21: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/home/gzx/workspace/bench2drive/carla/CarlaUE4.sh -RenderOffScreen -nosound -carla-rpc-port=30000 -graphicsadapter=0 None
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
load_world success , attempts=0
traffic_manager init success, try_time=0
leaderboard/leaderboard/leaderboard_evaluator.py:115: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.10'):
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 559, in <module>
    main()
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 548, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 121, in __init__
    self.module_agent = importlib.import_module(module_name)
  File "/home/gzx/anaconda3/envs/pt/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gzx/workspace/bench2drive/Bench2Drive/leaderboard/team_code/vad_b2d_agent.py", line 17, in <module>
    from Bench2DriveZoo.team_code.pid_controller import PIDController
ModuleNotFoundError: No module named 'Bench2DriveZoo'

```

**Comment by happytianhao** [comment]
> Hi, i follow this [EVAL Doc](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/EVAL_IN_CARLA.md) but in Bench2Drive/scenario_runner/srunner/scenariomanager/carla_data_provider.py line 22, raise an error:
> 
> ```shell
> from agents.navigation.global_route_planner import GlobalRoutePlanner
> ModuleNotFoundError: No module named 'agents'
> ```
> 
> Do i need to rebuild the bench2drivezoo or something else？

在Bench2Drive/leaderboard/scripts/run_evaluation.sh中设置一下CARLA_ROOT~
