### ISSUE TITLE
python version required 

### ISSUE THREAD

**Issue by ping28198** [Thinklab-SJTU/Bench2Drive#42]
hi, I want to eval in carla, with:
`bash leaderboard/scripts/run_evaluation_debug.sh`
agents module is required, which require tensorflow 1.x. 

my enviroment is python3.8 , it is not compatable with  tensorflow 1.x (only avaliable in python3.7). 

can you provide detiled requirements.txt

**Comment by ping28198** [comment]
sorry, agents is a submodule of carla， not a independent module。

**Comment by AvinsWang** [comment]
@ping28198  How did you sulve it? I have the same problem when I run `bash leaderboard/scripts/run_evaluation.sh`, Can you give me some advice
> Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 26, in <module>
    from srunner.scenariomanager.carla_data_provider import *
  File "/code/bev/Bench2Drive/scenario_runner/srunner/scenariomanager/carla_data_provider.py", line 22, in <module>
    from agents.navigation.global_route_planner import GlobalRoutePlanner
ModuleNotFoundError: No module named 'agents'

**Comment by cxiang26** [comment]
@ping28198 

I got the same problem, are you solved it?
