### ISSUE TITLE
module 'carla' has no attribute 'TrafficLightState'

### ISSUE THREAD

**Issue by YiHuang108** [Thinklab-SJTU/Bench2Drive#47]
I have once tried the CARLA for closed-loop evaluation, however, i failed at the second time, it displayed:

```
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 31, in <module>
    from leaderboard.scenarios.route_scenario import RouteScenario
  File "/media/Bench2Drive/leaderboard/leaderboard/scenarios/route_scenario.py", line 29, in <module>
    from srunner.scenariomanager.scenarioatomics.atomic_behaviors import ScenarioTriggerer, Idle
  File "/media/Bench2Drive/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py", line 3556, in <module>
    class TrafficLightManipulator(AtomicBehavior):
  File "/media/Bench2Drive/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py", line 3569, in TrafficLightManipulator
    RED = carla.TrafficLightState.Red
AttributeError: module 'carla' has no attribute 'TrafficLightState'
```
my run_evalation_debug.sh is:
```
#!/bin/bash
BASE_PORT=30000
BASE_TM_PORT=50000
IS_BENCH2DRIVE=True
BASE_ROUTES=leaderboard/data/bench2drive220
TEAM_AGENT=team_code/vad_b2d_agent.py
TEAM_CONFIG=my_team_agent_config.py+my_team_agent_ckpt.pth # for UniAD and VAD
BASE_CHECKPOINT_ENDPOINT=eval
SAVE_PATH=./eval_v1/
PLANNER_TYPE=only_traj

GPU_RANK=0
PORT=$BASE_PORT
TM_PORT=$BASE_TM_PORT
ROUTES="${BASE_ROUTES}.xml"
CHECKPOINT_ENDPOINT="${BASE_CHECKPOINT_ENDPOINT}.json"
bash leaderboard/scripts/run_evaluation.sh $PORT $TM_PORT $IS_BENCH2DRIVE $ROUTES $TEAM_AGENT $TEAM_CONFIG $CHECKPOINT_ENDPOINT $SAVE_PATH $PLANNER_TYPE $GPU_RANK
```

**Comment by jayyoung0802** [comment]
Which version is carla？Can you provide more details about this?

**Comment by YiHuang108** [comment]
0.9.15，I reinstall carla today and it works as it used to be.
