### ISSUE TITLE
RuntimeError: time-out of 600000ms while waiting for the simulator

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#72]
During the evaluation of VAD, `RuntimeError` occurs after running 75 clips, how to solve it? Thanks so much!

the whole ouput:

`exception in thread Thread-30:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/b2d_zoo/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/envs/b2d_zoo/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/new_Bench2Drive/Bench2Drive/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in build_scenarios_loop
    self.scenario.spawn_parked_vehicles(self.ego_vehicles[0])
  File "/home/user/new_Bench2Drive/Bench2Drive/leaderboard/leaderboard/scenarios/route_scenario.py", line 236, in spawn_parked_vehicles
    for response in CarlaDataProvider.get_client().apply_batch_sync(new_parked_vehicles):
RuntimeError: time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450
ERROR: failed to destroy actor 65547 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65548 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65549 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65551 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65538 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65539 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65540 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65541 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65542 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65543 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65544 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65545 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
ERROR: failed to destroy actor 65546 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 
`

**Comment by scuizhibin** [comment]
> During the evaluation of VAD, `RuntimeError` occurs after running 75 clips, how to solve it? Thanks so much!
> 
> the whole ouput:
> 
> `exception in thread Thread-30: Traceback (most recent call last): File "/home/user/anaconda3/envs/b2d_zoo/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run() File "/home/user/anaconda3/envs/b2d_zoo/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/home/user/new_Bench2Drive/Bench2Drive/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in build_scenarios_loop self.scenario.spawn_parked_vehicles(self.ego_vehicles[0]) File "/home/user/new_Bench2Drive/Bench2Drive/leaderboard/leaderboard/scenarios/route_scenario.py", line 236, in spawn_parked_vehicles for response in CarlaDataProvider.get_client().apply_batch_sync(new_parked_vehicles): RuntimeError: time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65547 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65548 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65549 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65551 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65538 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65539 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65540 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65541 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65542 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65543 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65544 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65545 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 ERROR: failed to destroy actor 65546 : time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30450 `

我还没有解决这个问题

**Comment by jayyoung0802** [comment]
refer to #32

**Comment by starlighttt123** [comment]
> refer to #32

感谢作者回复，看了下我的问题和这个issue好像不太一样，他的是carla无法正常启动，我的是评测进行到一半后断掉，并且两次断掉的时间相同（使用单卡单clip评测挂在第37，使用单卡双clip挂在第74）（注：./CarlaUE4.sh是运行正常的）

**Comment by jiaxiaosong1002** [comment]
@starlighttt123 You should resume evaluation.  CARLA has serious memory leakage issue.  It naturally could not run for a long time.  We have to conduct evaluation part by part as well, which is why we write robust and resumable code.

**Comment by Eden-Wang1710** [comment]
> @starlighttt123 You should resume evaluation. CARLA has serious memory leakage issue. It naturally could not run for a long time. We have to conduct evaluation part by part as well, which is why we write robust and resumable code.

Hi，if CARLA crashes， can we directly run` run_evaluation_multi_uniad.sh` to resume it？Will it detect which route is completed and resume the route with half process？Thanks！

**Comment by jayyoung0802** [comment]
Sure you can @Eden-Wang1710 , please refer to #89.

**Comment by TianleLiu0303** [comment]
请问resume后，是否会重新运行评估之前没有完成的route

**Comment by jayyoung0802** [comment]
Hi @TianleLiu0303, sure, it will.  And if one route always crashes, you can refer to #89.

**Comment by TianleLiu0303** [comment]
感谢回复，那是不是如果不跳过上次的冲突route，重启后有概率加载成功

**Comment by jayyoung0802** [comment]
Yes, have a try.

**Comment by TianleLiu0303** [comment]
但是我在重启后发现，相同的路径下，同样之前测评完成的route还会重新测评，请问是要把文件夹的路径修改成同样的名字吗

<img width="744" height="264" alt="Image" src="https://github.com/user-attachments/assets/0e6b646e-1299-4647-90e9-ab3dc6dbf101" />

**Comment by jayyoung0802** [comment]
No, just run it and make sure splite_xml is unchanged.

**Comment by TianleLiu0303** [comment]
However, the information in the figure shows that the path folder RouteScenario_2416_rep0_Town12_VanillaNonSignalizedTurnEncounterStopsign was created three times, with only the timestamp being different.

**Comment by deadlykitten4** [comment]
Hi @TianleLiu0303, 我想问下你成功评估所有的路线了吗？我发现只能评估185条，想请教下你是如何解决的
